/* Browser audit of the extracted ZIP. Screenshots + JSON per page; no hardware claims. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
const site=process.env.DPVR_SITE||'/workspace/delivery/unpacked/DpvrDeveloperNew/public';
const out=process.env.DPVR_AUDIT||'/workspace/delivery/evidence';fs.mkdirSync(out,{recursive:true});
function files(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(path.join(d,x.name)):[path.join(d,x.name)])}
const pages=files(site).filter(x=>x.endsWith('.html')).map(x=>path.relative(site,x).split(path.sep).join('/')).sort();
const rows=[],tasks=[];const assert=(x,m)=>{if(!x)throw Error(m)};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_BIN||'/usr/bin/chromium',args:['--no-sandbox']});
for(const mode of ['root','sub'])for(const mobile of [false,true]){
 const size=mobile?'mobile':'desktop',folder=path.join(out,mode+'-'+size);fs.mkdirSync(folder,{recursive:true});let next=0;
 await Promise.all(Array.from({length:4},async()=>{const page=await b.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}});page.setDefaultTimeout(10000);let errors=[],network=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>network.push({url:r.url(),error:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)network.push({url:r.url(),status:r.status()});if(r.status()!==304&&/\.(css|js|png|jpg)(\?|$)/.test(r.url())){const mime=r.headers()['content-type']||'';if(/\.css/.test(r.url())&&!mime.includes('text/css'))network.push({url:r.url(),mime});if(/\.js/.test(r.url())&&!/javascript/.test(mime))network.push({url:r.url(),mime})}});
 while(next<pages.length){const i=next++,p=pages[i];errors=[];network=[];const url=(mode==='root'?'http://127.0.0.1:8767/':'http://127.0.0.1:8768/dpvr-resources/')+p;
 try{const response=await page.goto(url);await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({headerHeight:document.querySelector('.site-header').getBoundingClientRect().height,headerColor:getComputedStyle(document.querySelector('.site-header')).backgroundColor,background:getComputedStyle(document.body).backgroundColor,css:document.styleSheets.length,search:window.DPVR_SEARCH?.length||0,overflow:document.documentElement.scrollWidth>innerWidth+1,title:document.querySelector('main h1')?.textContent,bodyChars:document.querySelector('main')?.textContent.length,brokenImages:[...document.images].filter(x=>x.getAttribute('src')&&(!x.complete||!x.naturalWidth)).map(x=>x.getAttribute('src')),tables:document.querySelectorAll('main table').length,code:document.querySelectorAll('main pre').length}));
 let violations=[];if(response.status()!==200)violations.push('HTTP status');if(metrics.headerColor!=='rgb(0, 0, 0)'||metrics.headerHeight!==90||!metrics.css)violations.push('CSS/header');if(metrics.search!==506)violations.push('search data');if(metrics.overflow)violations.push('page overflow');if(metrics.brokenImages.length)violations.push('image');if(!metrics.title||!metrics.bodyChars)violations.push('empty main');if(errors.length||network.length)violations.push('runtime/network');
 const screenshot=mode==='root'?path.relative(out,path.join(folder,String(i).padStart(3,'0')+'.jpg')):null;
 if(screenshot)await page.screenshot({path:path.join(out,screenshot),type:'jpeg',quality:55,animations:'disabled'});
 rows.push({mode,size,page:p,status:violations.length?'FAIL':'PASS',violations,metrics,errors:[...errors],network:[...network],screenshot});
 }catch(e){rows.push({mode,size,page:p,status:'FAIL',error:e.message})}
 if(i%64===0)console.log(mode,size,i,'/',pages.length);
 }await page.close()}));
 fs.writeFileSync(path.join(out,'browser-pages.json'),JSON.stringify(rows,null,2));
}
const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(10000);const root='http://127.0.0.1:8767/';
async function task(name,fn){try{await fn();tasks.push({name,status:'PASS'})}catch(e){tasks.push({name,status:e.message.includes('BLOCKED_BY_ENVIRONMENT')?'BLOCKED':'FAIL',error:e.message});console.log(name,e.message)}}
await task('file:// execution attempt',async()=>{try{await p.goto('file://'+site+'/index.html')}catch(e){throw Error('BLOCKED_BY_ENVIRONMENT: '+e.message)}assert(await p.evaluate(()=>window.DPVR_SEARCH?.length===506),'Offline search data')});
for(const base of [root,'http://127.0.0.1:8768/dpvr-resources/']){
 await task(base+' DMS first-call journey',async()=>{await p.goto(base+'index.html');await p.locator('main a[href$="resources/dm.html"]').first().click();await p.locator('main a[href$="guides/dms-android.html"]').first().click();const text=await p.locator('main').innerText();for(const s of ['MainActivity.java','setDeviceManagerResultListener','setDeviceManagerEventListener','systemInfoJobs','GetSerialNo','jobID','returnCode','onDestroy','unbindService'])assert(text.includes(s),s);await p.locator('main a[href$="GetSerialNo.html"]').first().click();assert((await p.locator('main').innerText()).includes('APP_PERMISSION_NORMAL'),'Permission');await p.locator('.language-link').click();assert(p.url().includes('/en/docs/dm/Apis/systemInfoJobs/GetSerialNo.html'),'Same article translation')});
 await task(base+' search body and deep navigation',async()=>{await p.goto(base+'cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html');await p.locator('.search-open').click();await p.locator('#search-query').fill('GetSerialNo');await p.locator('.search-result').first().click();assert(p.url().endsWith('/GetSerialNo.html'),'Search target');await p.locator('.search-open').click();await p.locator('#search-query').fill('AutoVideoPlay');assert(await p.locator('.search-result').count()>0,'Body search');assert((await p.locator('.search-result p').first().innerText()).includes('AutoVideoPlay'),'Body snippet');await p.keyboard.press('Escape')});
 await task(base+' TF configuration to playback',async()=>{await p.goto(base+'cn/docs/copy/copy-tool-guide.html');const text=await p.locator('main').innerText();for(const s of ['CopyTool.apk','copy_config.json','APK','ZIP_UNPACK','FILE','OBB','LANGUAGE_PACKAGE','OTA_PACKAGE'])assert(text.includes(s),s);await p.goto(base+'cn/guides/video-deploy.html');assert((await p.locator('main h1').innerText()).includes('播放器启动时'),'Correct startup title');assert(await p.locator('#tf-deploy').count(),'TF deployment section');assert((await p.locator('main').innerText()).includes('不支持P1 Max'),'TF restriction');const blocks=await p.locator('pre code').allTextContents();assert(blocks.filter(x=>{try{JSON.parse(x);return true}catch{return false}}).length>=2,'Playable and copy JSON');assert((await p.locator('main').innerText()).includes('不会让头显开机后自动启动播放器'),'No boot claim')});
 await task(base+' RDC and Gesture documented journeys',async()=>{await p.goto(base+'cn/guides/rdc-csharp.html');const text=await p.locator('main').innerText();for(const s of ['TCP','HTTP'])assert(text.includes(s),s);await p.goto(base+'cn/guides/gesture-start.html');assert(await p.locator('main table tbody tr').count()===4,'Four actions');const t=await p.locator('main').innerText();for(const s of ['V_SIGN / Vsign','OPEN_PALM','FIST','THUMBS_UP','放大','缩小','颜色','Assets/Plugins/Android','SampleScene.unity'])assert(t.includes(s),s)});
 await task(base+' copy button and image enlargement',async()=>{await p.goto(base+'cn/guides/video-deploy.html');await p.locator('.copy-code').first().click();assert((await p.locator('.copy-code').first().innerText()).includes('已复制'),'copy acknowledged');await p.goto(base+'cn/docs/cast/screen-casting.html');await p.locator('.article-body img').first().click();assert(await p.locator('.image-dialog').isVisible(),'image dialog');await p.keyboard.press('Escape');assert(!await p.locator('.image-dialog').isVisible(),'dialog closed')});
 await task(base+' all legacy resource hashes',async()=>{const map={'content-device-manager':'dm','content-aio-go2':'go2','content-aio-go':'go','content-screen-cast':'cast','content-encryption':'encryption','content-play-config':'playback','content-copy':'copy','content-remote':'rdc','content-plugin':'player','content-gesture':'gesture'};for(const [hash,id]of Object.entries(map)){await p.goto(base+'resource.html#'+hash);await p.waitForURL('**/cn/resources/'+id+'.html')}});
}
await p.setViewportSize({width:390,height:844});await task('Mobile drawers, navigation and search',async()=>{await p.goto(root+'cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html');await p.locator('.global-toggle').click();assert(await p.locator('.global-toggle').getAttribute('aria-expanded')==='true','global');await p.keyboard.press('Escape');await p.locator('.reader-menu').click();assert(await p.locator('.product-nav').getAttribute('aria-hidden')==='false','doc nav');await p.keyboard.press('Escape');await p.locator('.toc-menu').click();await p.locator('.page-toc a').filter({hasText:'Result'}).click();assert(await p.locator('.toc-menu').getAttribute('aria-expanded')==='false','toc closes');await p.locator('.search-open').click();await p.locator('#search-query').fill('GetSerialNo');await p.locator('.search-result').first().click();assert(p.url().endsWith('/GetSerialNo.html'),'mobile search')});
for(const width of [768,1024,1188])await task('Intermediate viewport '+width,async()=>{await p.setViewportSize({width,height:1000});for(const u of ['cn/index.html','cn/resources/dm.html','cn/docs/copy/copy-tool-guide.html']){await p.goto(root+u);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+u)}});
for(const mobile of [false,true]){await p.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:1000});for(const [name,u] of [['index','cn/index.html'],['dms','cn/guides/dms-android.html'],['serial','cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html'],['tf','cn/docs/copy/copy-tool-guide.html'],['playback','cn/guides/video-deploy.html'],['rdc','cn/guides/rdc-csharp.html'],['gesture','cn/guides/gesture-start.html'],['encryption','en/docs/encryption/gui-user-manual.html']]){await p.goto(root+u);await p.screenshot({path:path.join(out,name+'-'+(mobile?'mobile':'desktop')+'.png'),fullPage:true})}}
await b.close();fs.writeFileSync(path.join(out,'browser-tasks.json'),JSON.stringify(tasks,null,2));const summary={pageVisits:rows.length,pageFailures:rows.filter(x=>x.status==='FAIL').length,tasks,notTested:['Headset and SDK execution','Windows-native browser','External download contents']};fs.writeFileSync(path.join(out,'browser-summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));})().catch(e=>{console.error(e);process.exitCode=1});
