/* Representative real user tasks. Reports and screenshots stay outside the repository. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
const base=process.env.DPVR_PREVIEW_URL||'http://127.0.0.1:8766',out='/workspace/dpvr-new-review';fs.mkdirSync(out,{recursive:true});
const checks=[],errors=[],observations=[{severity:'usability',finding:'原“查看对应说明”已改语义阅读链接；TF/播放器步骤已增加章节锚点。',suggestion:'继续以真实任务验证锚点与对应步骤内容，而不是只核对页面存在。'},{severity:'clarity',finding:'GetSerialNo原文Params仍完整保留；新版API元数据与首例说明补充无参数说明。',suggestion:'继续将整理提示与原文分开，避免把补充内容冒充官方正文。'}];
const assert=(v,m)=>{if(!v)throw Error(m)};async function test(name,fn){try{checks.push({name,status:'PASS',evidence:await fn()||''})}catch(e){checks.push({name,status:'FAIL',evidence:e.message});console.log('FAIL '+name+' '+e.message)}}
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));const go=async p=>{const r=await page.goto(base+p);assert(r.status()===200,'HTTP '+r.status()+' '+p)};const main=()=>page.locator('main').innerText();
await test('首页→DMS→Android：两次点击',async()=>{await go('/cn/index.html');await page.locator('main a[href="/cn/resources/dm.html"]').first().click();await page.waitForURL('**/cn/resources/dm.html');await page.locator('main a[href="/cn/guides/dms-android.html"]').first().click();await page.waitForURL('**/cn/guides/dms-android.html');assert((await main()).includes('绑定服务并先注册 listener'),'Android接入引导缺失');return '首页资源卡→DMS概览→Android入口，2次点击进入整理后的Android接入引导'});
await test('Android完整教程：同页代码、两语同文与生命周期',async()=>{for(const lang of ['cn','en']){await go('/'+lang+'/guides/dms-android.html');const t=await main();for(const word of ['MainActivity.java','APP_PERMISSION_NORMAL','DeviceManagerKey','setDeviceManagerResultListener','setDeviceManagerEventListener','systemInfoJobs','GetSerialNo','jobID','returnCode','getString("sn")','onDestroy','unbindService'])assert(t.includes(word),'完整教程缺少 '+lang+' '+word);assert(await page.locator('.article-body pre').count()>=3,'缺少完整可读代码');const code=await page.locator('.article-body pre').last().innerText();assert(code.includes('public final class MainActivity'),'缺完整Activity');assert(code.indexOf('setDeviceManagerResultListener(resultListener)')<code.indexOf('readSerialNumber();'),'未先listener后call')}await page.locator('.language-link').click();await page.waitForURL('**/cn/guides/dms-android.html');return '两语含完整Activity/Manifest/AIDL配置、绑定及异步结果解析；仅文档验证，未编译运行'});
await test('DMS教程：权限→绑定/监听→首个NORMAL读取',async()=>{await go('/cn/guides/dms-android.html');const h=await page.locator('.article-body h2').allInnerTexts();assert(h.findIndex(x=>x.includes('NORMAL'))<h.findIndex(x=>x.includes('绑定服务')),'学习依赖顺序错误');await page.locator('main a[href*="GetSerialNo.html"]').first().click();await page.waitForURL('**/GetSerialNo.html');const api=await main();assert(api.includes('APP_PERMISSION_NORMAL'),'首个验证接口不是NORMAL');assert(api.includes('设备sn号')&&api.includes('String'),'缺少预期返回值');return '完整教程NORMAL确认先于绑定/监听；GetSerialNo结果sn:String'});
await test('接口搜索GetSerialNo及参数/结果定位',async()=>{await page.locator('.search-open').click();await page.locator('#search-query').fill('GetSerialNo');await page.waitForSelector('.search-result');const first=page.locator('.search-result').first();assert((await first.innerText()).includes('GetSerialNo'),'精准API结果未排首位');await first.click();await page.waitForURL('**/GetSerialNo.html');const headings=await page.locator('.article-body h2').allInnerTexts();assert(headings.some(h=>h.includes('Params'))&&headings.some(h=>h.includes('Result')),'参数/结果节缺失');assert(await page.locator('.page-toc a').count()>=3,'接口缺少目录定位');return '精准API优先；Permission/Params/Result可由目录定位，Params源文为空，整理提示补充说明'});
await test('语言切换保留同一API',async()=>{await page.locator('.language-link').click();await page.waitForURL('**/en/docs/dm/Apis/systemInfoJobs/GetSerialNo.html');assert((await main()).includes('GetSerialNo'),'切换后丢失同文');await page.locator('.language-link').click();await page.waitForURL('**/cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html')});
await page.screenshot({path:path.join(out,'task-api-desktop.png'),fullPage:true});
await test('TF任务：配置字段→落机位置→OTA边界',async()=>{await go('/cn/resources/copy.html');let t=await main();assert(t.includes('CopyTool.apk')&&t.includes('TF 卡根目录'),'前置安装/配置位置不清楚');assert(t.includes('OTA_PACKAGE')&&t.includes('只复制升级包')&&t.includes('不会触发固件升级'),'OTA行为边界缺失');await page.locator('main a[href="/cn/docs/copy/copy-tool-guide.html"]').first().click();t=await main();for(const s of ['source','dist','${EXT_SD}','copy_config.json','TF 卡根目录','自动加载配置'])assert(t.includes(s),'TF指南缺少 '+s);await go('/cn/docs/copy/configuration-example.html');assert((await main()).includes('source')&&(await main()).includes('type'),'配置样例缺少真实字段');return '安装APK、source/dist、TF根目录、插卡执行与OTA仅复制均可读；未在真实设备执行'});
await test('RDC概览：按控制端能力选库或协议',async()=>{await go('/cn/resources/rdc.html');const t=await main();for(const s of ['Windows 64 位 .NET 7','其他平台','TCP','RDC 服务','同一广播域','HTTP/HTTPS'])assert(t.includes(s),'路线/条件缺少 '+s);assert(await page.locator('main a[href="/cn/docs/rdc/lib_dev/RDCLib.html"]').count()>0,'无库路线入口');assert(await page.locator('main a[href="/cn/docs/rdc/server_dev/index.html"]').count()>0,'无协议路线入口');await page.locator('main a[href="/cn/docs/rdc/lib_dev/RDCLib.html"]').first().click();await page.waitForURL('**/cn/docs/rdc/lib_dev/RDCLib.html');assert((await main()).includes('基于RDC库的服务端开发'),'RDC库正文未到达');return '概览选择依据及库正文入口均可用'});
await test('RDC C#引导：服务→网络→监听→单设备→状态',async()=>{await go('/cn/guides/rdc-csharp.html');const t=await main();let previous=-1;for(const word of ['核对设备端服务','设置网络','选择匹配','先注册监听','明确目标','检查状态']){const index=t.indexOf(word);assert(index>previous,'RDC步骤顺序异常 '+word);previous=index}for(const word of ['com.deepoon.eggchair','AUTO FIND','OnConnectStateChangedEvent','GetClient','DeviceSetVolume','ConnectState','HTTP'])assert(t.includes(word),'RDC引导缺少 '+word);return '已检查应用服务、网络、监听、目标SN及单设备列表、状态确认；未实际执行C#或设备操作'});
await test('手势任务：先条件，再SampleScene，再可观察反馈',async()=>{await go('/cn/guides/gesture-start.html');const t=await main();const condition=t.indexOf('准备条件'),scene=t.indexOf('SampleScene.unity'),expected=t.indexOf('V_SIGN');assert(condition>=0&&scene>condition&&expected>scene,'手势步骤前置顺序错误');for(const s of ['P1 Pro 4K Camera','Multithreaded Rendering','相机权限','Assets/Plugins/Android','Build And Run','OPEN_PALM','FIST','THUMBS_UP'])assert(t.includes(s),'缺少手势条件或预期 '+s);return '正确Camera型号、相机权限、多线程关闭先确认；真机示例后检查四种交互'});
await test('视频任务：当前页完整JSON、设备目录与验证',async()=>{await go('/cn/guides/video-deploy.html');const t=await main();for(const word of ['AutoPlayDisposition.json','/sdcard/demo.mp4','AutoVideoPlay','播放器启动时读取配置','videoModel','showUI','只复制升级包'])assert(t.includes(word),'视频原地任务缺少 '+word);const json=await page.locator('.article-body pre code').first().innerText();assert(JSON.parse(json).videoPath==='/sdcard/demo.mp4','JSON不是完整可解析配置');await page.screenshot({path:path.join(out,'task-video-desktop.png'),fullPage:true});return '同页JSON可解析、目录树与单设备验证完整；设备播放未测'});
await test('RDC与手势实际流程截图',async()=>{for(const name of ['rdc-csharp','gesture-start']){await go('/cn/guides/'+name+'.html');await page.screenshot({path:path.join(out,'task-'+name+'-desktop.png'),fullPage:true});assert(await page.locator('main h2, main h3').count()>=3,'缺少流程章节')}return '已保存当前真实指南完整截图，不声称设备运行验证'});
await page.setViewportSize({width:390,height:844});
await test('手机设备过滤：P2与Camera不混淆',async()=>{await go('/cn/index.html');await page.locator('#device-filter').selectOption('P2');let cards=page.locator('.resource-card:visible');assert(await cards.count()>0,'P2过滤为空');for(const d of await cards.evaluateAll(a=>a.map(x=>JSON.parse(x.dataset.devices))))assert(d.includes('P2'),'出现不支持P2的卡片');assert(await page.locator('.resource-card:visible a[href="/cn/resources/gesture.html"]').count()===0,'P2错误包含Camera手势');await page.locator('#device-filter').selectOption('P1 Pro 4K Camera');assert(await page.locator('.resource-card:visible').count()===1,'Camera型号过滤结果不准确');assert(await page.locator('.resource-card:visible a[href="/cn/resources/gesture.html"]').count()>0,'Camera找不到手势');await page.reload();assert(await page.locator('#device-filter').inputValue()==='P1 Pro 4K Camera','过滤条件刷新丢失')});
await page.screenshot({path:path.join(out,'task-filter-mobile.png'),fullPage:true});
await test('手机全局导航、文档导航与TOC',async()=>{await go('/cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html');await page.locator('.global-toggle').click();assert(await page.locator('.global-toggle').getAttribute('aria-expanded')==='true','全局导航无法展开');await page.keyboard.press('Escape');await page.locator('.reader-menu').click();assert(await page.locator('.reader-menu').getAttribute('aria-expanded')==='true','文档导航打不开');assert(await page.locator('.product-nav').isVisible(),'产品导航不可见');await page.keyboard.press('Escape');await page.locator('.toc-menu').click();assert(await page.locator('.toc-menu').getAttribute('aria-expanded')==='true','TOC打不开');await page.locator('.page-toc a').filter({hasText:'Result'}).click();assert(new URL(page.url()).hash,'TOC结果跳转失败');assert(await page.locator('.toc-menu').getAttribute('aria-expanded')==='false','TOC选择后未关闭');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'手机整页横向溢出')});
await test('手机搜索并回到同文',async()=>{await page.locator('.search-open').click();await page.locator('#search-query').fill('GetSerialNo');await page.waitForSelector('.search-result');await page.locator('.search-result').first().click();await page.waitForURL('**/cn/docs/dm/Apis/systemInfoJobs/GetSerialNo.html');assert((await main()).includes('设备SN号'),'手机API搜索未落到预期内容')});
await page.screenshot({path:path.join(out,'task-api-mobile.png'),fullPage:true});
await test('浏览器无未捕获异常',async()=>assert(errors.length===0,errors.join('\n')));
}finally{await browser.close()};const report={timestamp:new Date().toISOString(),scope:'Representative browser task review on the full generated site. Full corpus static validation is reported separately; no device/SDK execution claims.',checks,observations,errors,not_tested:['全量正文逐页交互（另有474页静态原文与链接校验）','真实头显AIDL/Unity/TF/网络执行','外部下载文件内容与可达性'],passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length};fs.writeFileSync(path.join(out,'tasks.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'tasks.md'),'# 代表页面真实任务验收\n\n'+checks.map(x=>'- '+x.status+' '+x.name+'：'+x.evidence).join('\n')+'\n\n## UX观察\n\n'+observations.map(x=>'- '+x.finding+' 建议：'+x.suggestion).join('\n')+'\n\n## 未测\n\n'+report.not_tested.map(x=>'- '+x).join('\n')+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1});
